**Make a duplicate copy of google colab by clicking File/ Save a copy in Drive option. A duplicate copy will get created. It will open up in the new tab on your web browser .After that change share settings**

1. Write  code to
    a)Create different numeric data , print its value and type

    b) Perform addition subtraction multiplication and division on numbers in Python

 2. Write code to
    1. Create a list contain Reg No., Name and Mark of 2 subjects(out of 100) of a student and Append one more mark to the  
    2. Print the list

In [ ]:
#write your code here

** 3. Update the value of the second mark**

In [ ]:
#write your code here

** 4. Create a random list contain 10 elements with values between 40 and 80**

In [ ]:
#write your code here

** 5. Decrement the value of each element in the above list**

In [ ]:
#write your code here

**Create a dictionary  store the Name, City and Mobilw number of a person
Print the Name and Mobile number**

In [ ]:
#wite your code here